### ISSUE TITLE
FOAM FATAL ERROR: (openfoam-2206) in M1 Ultra

### ISSUE THREAD

**Issue by kohyun** [BrushXue/OpenFOAM-AppleM1#6]
Hi,

I have compiled openfoam-2206 in my M1 Ultra.

I can run openfoam-2206 with serial mode.
But, in parallel mode, I have the following FATAL Error.

Are there any missing points?

--> FOAM FATAL ERROR: (openfoam-2206)
The dummy Pstream library cannot be used in parallel mode

    From static bool Foam::UPstream::init(int &, char **&, const bool)
    in file UPstream.C at line 49.

FOAM exiting

**Comment by BrushXue** [comment]
Could you provide the compile log?

**Comment by drhcelik** [comment]
I don't know if this is something specific to OF-M1 repository, but in normal OF compilation, this error occurs due to mixed up OpenMPI definitions. For instance, when you have compiled OpenMPI in ThirdParty folder and you try to use SYSTEMOPENMPI in etc/bashrc or vice versa.

**Comment by kohyun** [comment]
> 

Here is the compile log.

Hope it could help.

[log.darwinARM64ClangDPInt32Opt.log](https://github.com/BrushXue/OpenFOAM-AppleM1/files/9753269/log.darwinARM64ClangDPInt32Opt.log)

**Comment by BrushXue** [comment]
Hello @kohyun. Your log doesn't show anything. But same with @drhcelik, you should only use `openmpi` from homebrew. Otherwise there will be strange error like this.

I don't know if M1 Ultra has anything special because it's two M1 glued together. Can you run `brew test open-mpi` to see if it's actually working?

**Comment by kohyun** [comment]
Hi @BrushXue 

The followings are result of "brew test open-mpi"

hyunko@HYUNs-Mac-Studio test % brew test open-mpi
==> Testing open-mpi
==> /opt/homebrew/Cellar/open-mpi/4.1.4_1/bin/mpicc hello.c -o hello
==> ./hello
==> /opt/homebrew/Cellar/open-mpi/4.1.4_1/bin/mpirun ./hello
==> /opt/homebrew/Cellar/open-mpi/4.1.4_1/bin/mpif90 hellof.f90 -o hellof
==> ./hellof
==> /opt/homebrew/Cellar/open-mpi/4.1.4_1/bin/mpirun ./hellof

**Comment by BrushXue** [comment]
Looks like there’s some changes from other components and I couldn’t compile it for now. I’ll update the patch when I have time.

**Comment by BrushXue** [comment]
OK after compiled it again I'm having the same issue.

**Comment by BrushXue** [comment]
Is it only happens when you are trying to run `mpirun` inside a script? Is the problem reproducible if you type it in the shell?
Try to run your parallel script by using this:
```
. $WM_PROJECT_DIR/bin/tools/RunFunctions
runParallel ***Foam
```

**Comment by kohyun** [comment]
Hi @BrushXue 

When I tried runParallel, it works.
mpirun still has problems, but runParallel works.

Thank you.

**Comment by BrushXue** [comment]
That's a macOS feature, not a bug.

By the way, would you mind running the benchmark (I just updated the file and it should run without problem) on your M1 Ultra and post the result on [CFDonline](https://www.cfd-online.com/Forums/hardware/198378-openfoam-benchmarks-various-hardware.html)? Don't forget to change number of cores.

**Comment by kohyun** [comment]
Sure.

just download the tar file and run/report?

**Comment by BrushXue** [comment]
You need to modify the number of cores in the script first. It's very straightforward.
