### ISSUE TITLE
您好，怎么在mac上安装 rheoTool 呢？安装出现错误

### ISSUE THREAD

**Issue by OP-ACE** [BrushXue/OpenFOAM-AppleM1#7]
提示错误如下： 

********************** 

Petsc has been downloaded successfully to directory:

/Users/pfg/OpenFOAM/pfg-v2212/ThirdParty/petsc-3.14.5

Using python3 for Python
===============================================================================
             Configuring PETSc to compile on your system                       
===============================================================================
TESTING: configureDirectories from PETSc.options.petscdir(config/PETSc/options/petscdir.py:23)                        *******************************************************************************
         UNABLE to CONFIGURE with GIVEN OPTIONS    (see configure.log for details):
-------------------------------------------------------------------------------
The environmental variable PETSC_DIR /usr/local/Cellar/petsc/3.15.4 MUST be the current directory /Users/pfg/OpenFOAM/pfg-v2212/ThirdParty/petsc-3.14.5
*******************************************************************************

非常感谢！
非常愿意有偿帮助在mac上编译rheoTool。

我的QQ 254679746

**Comment by BrushXue** [comment]
You'll need PETSc from homebrew

**Comment by BrushXue** [comment]
如果坚持要在Mac上面用rheoTool，建议你去编译Foundation版本：https://github.com/mrklein/openfoam-os-x/blob/master/OpenFOAM-9-2b1d7d67c.patch ，可能需要针对M1做一些修改。
rheoTool原作者拒绝适配ESI-OpenFOAM，现在两个版本之间差的太多了，移植工作量巨大，不要在这件事上浪费时间。
